base_url = "https://rawsp33d.github.io/oi"
title = "Oi"
description = "Friendly neighborhood programming language."

theme = "zap"
# theme = "adidoks"
# theme = "book"
# theme = "terminimal"

compile_sass = true
build_search_index = true

[markdown]

[markdown.highlighting]
light_theme = "github-light"
dark_theme = "github-dark"
theme = "github-dark"

[extra]

mode = "product"
github = "https://github.com/rawsp33d/oi"

keywords = ""

menu_links = [
	{ name = "/", url = "/" },
	{ name = "/about", url = "/about" },
	{ name = "/docs", url = "/docs/oi" },
]

theme_color = "#333"
