title = "Oi"
description = "Your friendly neighborhood programming language."
base_url = "https://rawsp33d.github.io/oi"

compile_sass = true
build_search_index = true

theme = "apollo"
# theme = "devlab"
# theme = "adidoks"
# theme = "book"
# theme = "terminimal"

taxonomies = [{ name = "tags" }]

[markdown]

[markdown.highlighting]
dark_theme = "github-dark"
light_theme = "github-light"

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[extra]

keywords = "oi, language, programming-language, compiler"

# apollo

fancy_code = true
theme = "toggle-auto"

stylesheets = ["style.css"]
socials = [
	{ name = "github", url = "https://github.com/rawsp33d/oi", icon = "github" },
]
menu = [
	{ name = "features", url = "/features" },
	{ name = "examples", url = "/examples" },
	{ name = "blog", url = "/blog" },
	{ name = "about", url = "/about" },
	{ name = "docs", url = "/docs/oi" },
]

[extra.analytics]
enabled = false

[extra.devlab.navigation]
links = [
	{ name = "home", path = "/" },
	{ name = "features", path = "/features" },
	{ name = "examples", path = "/examples" },
	{ name = "about", path = "/about" },
	{ name = "docs", path = "/docs/oi" },
]
